resolver: lts-7.8

packages:
- location: '.'

extra-deps:
- ghcjs-dom-0.7.0.3
- ghcjs-dom-jsaddle-0.7.0.3
- jsaddle-0.7.0.0
- jsaddle-dom-0.7.0.3
- jsaddle-warp-0.7.0.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1

nix:
  enable: true
